---
title: US_EM_MPS_spillover
authors:
  - name: Özer Karagedikli
    affiliation: 
    - name: Asia School of Business 
      country: Malaysia
    email:  ozer.karagedikli@asb.edu.my
  - name: Xolani Sibande
    affiliation: 
    - name: South Africa Reserve Bank
      department: Economic Research Department
      country: South Africa
    roles: writing
    corresponding: true
    email: xolani.sibande@resbank.co.za
abstract: |
  Ipsum. 
  \newline
  \newline
  **Keywords**: Monetary policy surprises \newline
  **JEL Codes**: J10, H1, K3 

bibliography: references.bib
number-sections: true
notebook-links: false
---

```{r}
# label: functions

library(here)
source(here("notebooks", "packages_script.R"))
source(here("notebooks","functions","modelsummary_pdf.R" ))
source(here("notebooks","functions","borderlines.R" ))
source(here("notebooks", "functions", "flextable_pdf.R"))

set_flextable_defaults(font.size = 8, 
                       text.align = "left", 
                       font.color = "black", 
                       theme_fun = theme_apa, 
                       padding = 0,
                       line_spacing = 0)
```

# Introduction

# Literature Review

@gurkaynak2005

# Data and Methodology

\newpage

# Results

```{r}
#label: ols_data

board <- board_gdrive("https://drive.google.com/drive/folders/1wlEf0FcbOSxjaoVxa8MFkE8aiSjSPMfA")

modeling_data <- pin_read(board, "artifacts_announcement_days_ols")

ols_models_tbl <- modeling_data |> pluck(1)
resid_models_tbl <- modeling_data |> pluck(2)
```

```{r}
#| label: tbl-ols_models
#| tbl-cap: "Ols models"
#| ft.arraystrech: .4
ols_models_tbl |> 
  dplyr::select(-`R^2`) |> 
  as_grouped_data(groups = c("group"), expand_single = TRUE) |> 
  as_flextable(hide_grouplabel = TRUE) |> 
  align(align = "left", part = "all") |> 
  align(align = "center", i = c("1", "5", "9")) |> 
  autofit(add_w = .9)

```

# Conclusion

\newpage

# Reference {.unnumbered}

::: {#refs}
:::

\setcounter{section}{0}
\renewcommand{\thesection}{\Alph{section}}
\setcounter{table}{0}
\renewcommand{\thetable}{A\arabic{table}}
\setcounter{figure}{0}
\renewcommand{\thefigure}{A\arabic{figure}}
\newpage

# Appendix

## Data

{{< embed notebooks/01_yields_data.qmd#fig-yields >}}

{{< embed notebooks/02_surprises_data.qmd#fig-surprises >}}

\newpage

## Residuals

{{< embed notebooks/04_ols_models.qmd#fig-residuals >}}
